### PR TITLE
Fix sidebar toolbaritem strange behaviour and addStory toolbar button

### LINKED ISSUE #5: Investiguate Toolbar
As a user,
I want to use items in the toolbar to enhance my experience

- Review the Collapse Sidebar button
- Add button to trigger new sprint

### PR DESCRIPTION
**Pull request by lucas-barbero**

### CODE REVIEW

File: RunningOrder/CustomWindow.swift [hunk 1]
```diff
@@ -13,29 +13,90 @@ import SwiftUI
...
+            .flexibleSpace,
+            .cloudSharing
         ]
     }
 
     func toolbar(_ toolbar: NSToolbar, itemForItemIdentifier itemIdentifier: NSToolbarItem.Identifier, willBeInsertedIntoToolbar flag: Bool) -> NSToolbarItem? {
-        let item = NSToolbarItem(itemIdentifier: itemIdentifier)
 
-        return item
+        var toolbarItem: NSToolbarItem = NSToolbarItem()
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift]: Could we agree on not specifying the type when it's not necessary?

File: RunningOrder/CustomWindow.swift [hunk 2]
```diff
@@ -13,29 +13,90 @@ import SwiftUI
...
+
+        if itemIdentifier == NSToolbarItem.Identifier.addStory {
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift]:
```suggestion
        if itemIdentifier == .addStory {
```

File: RunningOrder/CustomWindow.swift [hunk 3]
```diff
@@ -13,29 +13,90 @@ import SwiftUI
...
+            toolbarItem = customToolbarButtonItem(itemForItemIdentifier: itemIdentifier.rawValue,
+                                                  label: NSLocalizedString("Add a story", comment: ""),
+                                                  paletteLabel: NSLocalizedString("Add a story", comment: ""),
+                                                  toolTip: NSLocalizedString("Add a story", comment: ""),
+                                                  iconImageName: NSImage.addTemplateName,
+                                                  action: #selector(addStoryActionPlaceHolder))!
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift]: please avoid force unwrap

File: RunningOrder/CustomWindow.swift [hunk 4]
```diff
@@ -13,29 +13,90 @@ import SwiftUI
...
+        }
+
+        return toolbarItem
+    }
+
+    func toolbarWillAddItem(_ notification: Notification) {
+        let item = notification.userInfo!["item"] as? NSToolbarItem
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift]: do we really want to force unwrap?

Comment (bilalb) [inline RunningOrder/CustomWindow.swift]: do we really want to force unwrap?

File: RunningOrder/CustomWindow.swift [hunk 5]
```diff
@@ -13,29 +13,90 @@ import SwiftUI
...
+        if let item = item {
+            if item.itemIdentifier == NSToolbarItem.Identifier.toggleSidebar {
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift]: you can merge the two ifs :)

Comment (bilalb) [reply RunningOrder/CustomWindow.swift]:
```suggestion
            if item.itemIdentifier == .toggleSidebar {
```

File: RunningOrder/CustomWindow.swift [hunk 6]
```diff
@@ -13,29 +13,90 @@ import SwiftUI
...
     }
 
     override func windowDidLoad() {
         super.windowDidLoad()
 
         window?.contentViewController = NSHostingController(rootView: MainView())
     }
+
+    func customToolbarButtonItem(
+        itemForItemIdentifier itemIdentifier: String,
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift]: itemForItemIdentifier sounds weird :)

File: RunningOrder/CustomWindow.swift [hunk 7]
```diff
@@ -13,29 +13,90 @@ import SwiftUI
...
+        toolbarItem.view = button
+        toolbarItem.label = label
+        toolbarItem.paletteLabel = paletteLabel
+        toolbarItem.toolTip = toolTip
+        toolbarItem.target = self
+
+        return toolbarItem
+    }
+
+// TODO change these lines in the future
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift:101]: why not now? :p

**Review by zarghol — APPROVED** [review]
I really dislike the 
`((window?.contentView?.subviews.first?.subviews.first?.subviews.first as? NSSplitView)?.delegate as? NSSplitViewController)?.toggleSidebar(self)`

But we'll solve this later :)

**Review by bilalb — COMMENTED** [review]
Nice, just some minor comments :)

File: RunningOrder/CustomWindow.swift [hunk 8]
```diff
@@ -13,29 +13,90 @@ import SwiftUI
...
         window?.contentViewController = NSHostingController(rootView: MainView())
     }
+
+    func customToolbarButtonItem(
+        itemForItemIdentifier itemIdentifier: String,
+        label: String,
+        paletteLabel: String,
+        toolTip: String,
+        iconImageName: String,
+        action: Selector) -> NSToolbarItem? {
```
Comment (zarghol) [inline RunningOrder/CustomWindow.swift]: maybe this shouldn't return an optional

File: RunningOrder/CustomWindow.swift (hunk 7 above)
Comment (zarghol) [reply RunningOrder/CustomWindow.swift:101]: Because we don't know yet how to pass it to the SwiftUI views to do the job, and to handle correctly the toggling ^^'

File: RunningOrder/CustomWindow.swift [hunk 9]
```diff
@@ -13,29 +13,89 @@ import SwiftUI
...
+        toolTip: String,
+        iconImageName: String,
+        action: Selector) -> NSToolbarItem {
+
+        let toolbarItem = NSToolbarItem(itemIdentifier: NSToolbarItem.Identifier(rawValue: itemIdentifier))
+
+        let iconImage = NSImage(named: iconImageName)
+
+        let button = NSButton(frame: NSRect(x: 0, y: 0, width: 40, height: 40))
+        button.title = ""
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift:87]: is that line necessary?

File: RunningOrder/CustomWindow.swift [hunk 10]
```diff
@@ -13,29 +13,89 @@ import SwiftUI
...
+        button.image = iconImage
+        button.bezelStyle = .texturedRounded
+
+        button.action = action
+        toolbarItem.view = button
+        toolbarItem.label = label
+        toolbarItem.paletteLabel = paletteLabel
+        toolbarItem.toolTip = toolTip
+        toolbarItem.target = self
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift:96]: would we need to set another target? If so, it would make sense to extract the target to a parameter :)

**Review by bilalb — APPROVED** [review]

File: RunningOrder/CustomWindow.swift (hunk 9 above)
Comment (lucas-barbero) [reply RunningOrder/CustomWindow.swift:87]: Yes, otherwise the default text button is "Button"

File: RunningOrder/CustomWindow.swift [hunk 11]
```diff
@@ -10,32 +10,123 @@ import Cocoa
...
+}
+
+private extension NSToolbarItem.Identifier {
+    static let addStory = NSToolbarItem.Identifier(rawValue: "AddStory")
+}
+
+class CustomToolbarItem: NSToolbarItem {
+
+    override func validate() {
+        if let control = self.view as? NSControl, let action = self.action,
```
Comment (bilalb) [inline RunningOrder/CustomWindow.swift]: > For conciseness, avoid using self since Swift does not require it to access an object's properties or invoke its methods.
Use self only when required by the compiler (in @escaping closures, or in initializers to disambiguate properties from arguments). In other words, if it compiles without self then omit it.

We try to respect some conventions:

https://github.com/raywenderlich/swift-style-guide

https://swift.org/documentation/api-design-guidelines/

Comment (lucas-barbero) [reply RunningOrder/CustomWindow.swift]: 😠
